# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d7b68106b2df6eb5f0cf973b6c461b0049104068cc522ee742245f15b5c1c3510fc4d0c4accc55253a28dbc7c1d76abfc235dfaeee7cf5bcb8d5fa58f009a57f

test:
  secret_key_base: 3160d766eda4cfbbdabeb58727384b72bd618054f02a87a310f2b52d6b9153af9feaa8798b62e2b22bb493e05f6f537748ccc6898567a94609b1094b933ca1e3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
